In [47]:
import numpy as np
from numpy.random import rand, randn

## TASK A: Matrix standardisation function 

In [3]:
def normalise(matrix):
    result = np.zeros(matrix.shape) # careful to make a copy!
    matrix = matrix.astype(float)  # Convert the matrix to float data type
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            result[i, j] = (matrix[i, j] - np.mean(matrix[:, j])) / np.std(matrix[:, j])
    return result

#Vectorized version subtracts vectors from matrices using broadcasting
def normalise_vectorized(matrix):
    column_means = np.mean(matrix, axis=0)
    column_std = np.std(matrix, axis=0)
    standardized_matrix = (matrix - column_means) / column_std
    return standardized_matrix

# Example usage
myMatrix = np.array([[80, 77, 3], [23, 2, 3], [95, 5, 6], [30, 8, 9]])
print(normalise(myMatrix))
print(normalise_vectorized(myMatrix))


[[ 0.74058808  1.7280553  -0.90453403]
 [-1.09478239 -0.67202151 -0.90453403]
 [ 1.22358031 -0.57601843  0.30151134]
 [-0.86938601 -0.48001536  1.50755672]]
[[ 0.74058808  1.7280553  -0.90453403]
 [-1.09478239 -0.67202151 -0.90453403]
 [ 1.22358031 -0.57601843  0.30151134]
 [-0.86938601 -0.48001536  1.50755672]]


## Task B: Eucliden Distance function

In [4]:
myMatrixA = np.array([[1,2],[3,4],[5,6]])
myMatrixB = np.array([[2,3],[5,4],[9,6],[20,21]])

#Euclidean Distance
def euclideanDistance(matrixA, matrixB):
    distance = np.zeros((matrixA.shape[0], matrixB.shape[0]))
    for i in range(matrixA.shape[0]):
        for j in range(matrixB.shape[0]):
            distance[i,j] = np.sqrt(np.sum(np.square(matrixA[i] - matrixB[j])))
    return distance

euclideanDistance(myMatrixA, myMatrixB)

array([[ 1.41421356,  4.47213595,  8.94427191, 26.87005769],
       [ 1.41421356,  2.        ,  6.32455532, 24.04163056],
       [ 4.24264069,  2.        ,  4.        , 21.21320344]])

## Task C: Likelihood of a data sample under a Gaussian model

In [77]:

model_1 = (2,3)
model_2 = (3,4)

myMatrixA = np.array([[3,2],[3,2],[0,6]])
def multivariate_normal_pdf(mu,sigma,x):
    return 1 / (2 * np.pi)**(len(mu)/2) * 1 / np.sqrt(np.linalg.det(sigma)) * np.exp(-1/2 * np.dot(np.dot((x - mu).T, np.linalg.inv(sigma)), (x - mu)))

print(multivariate_normal_pdf(np.mean(myMatrixA, axis=0), np.cov(myMatrixA.T), np.array([1,2])))

def gaussian_classify(data, model_1,model_2):
    
    result = np.array
    #First we compute the vector mu
    mu = np.mean(data, axis=0)
    sigma = np.cov(data.T)

    #Likihood of the data given the model
    #model_1_prob = np.multivariate_normal.pdf(data, mean=model_1[0], cov=model_1[1])
    #model_2_prob = np.multivariate_normal.pdf(data, mean=model_2[0], cov=model_2[1])

    #return np.linalg.det(sigma)



#print(gaussian_classify(myMatrixA, model_1, model_2))

#np.linalg.det(myMatrixA)
    

nan


C:\Users\moham\AppData\Local\Temp/ipykernel_11156/3248152772.py:6: RuntimeWarning: invalid value encountered in sqrt
  return 1 / (2 * np.pi)**(len(mu)/2) * 1 / np.sqrt(np.linalg.det(sigma)) * np.exp(-1/2 * np.dot(np.dot((x - mu).T, np.linalg.inv(sigma)), (x - mu)))
C:\Users\moham\AppData\Local\Temp/ipykernel_11156/3248152772.py:6: RuntimeWarning: overflow encountered in exp
  return 1 / (2 * np.pi)**(len(mu)/2) * 1 / np.sqrt(np.linalg.det(sigma)) * np.exp(-1/2 * np.dot(np.dot((x - mu).T, np.linalg.inv(sigma)), (x - mu)))


In [123]:
import numpy as np
import scipy.stats as sp


def multivariate_normal_cdf(mu, sigma, x):
    """
    Compute the cumulative distribution function (CDF) of a multivariate Gaussian distribution.

    Parameters:
        mu (array): Mean vector of the distribution.
        sigma (array): Covariance matrix of the distribution.
        x (array): Point(s) at which to evaluate the CDF.

    Returns:
        cdf (float or array): CDF value(s) at the given point(s).
    """
    dist = sp.multivariate_normal(mean=mu, cov=sigma)
    cdf = dist.cdf(x)
    return cdf



# Define the mean vector and covariance matrix
mu = np.array([1, 2])
sigma = np.array([[2, 0.5], [0.5, 1]])

# Define an input vector
x = np.array([2, 3])

# Calculate the PDF
pdf_value = multivariate_normal_pdf(mu, sigma, x)

# Print the result
print("PDF value:", pdf_value)

np.random.seed(20)

X = rand(10,5) #Matrix of n x d
mu = np.mean(X, axis=0) #Vector of d
sigma = np.cov(X.T) #Matrix of d x d # sysmmetric matrix

model_1_mu = np.mean(X*0.5, axis=0)
model_1_sigma = np.cov(X.T*0.5)

model_2_mu = np.mean(X*-0.5, axis=0)
model_2_sigma = np.cov(X.T*-0.5)

def is_pos_def(x):
    return np.all(np.linalg.eigvals(x) >= 0)

print(model_1_mu)
print(model_1_sigma)
print(is_pos_def(model_1_sigma))
print(multivariate_normal_pdf(model_1_mu, model_1_sigma, np.array([0.26,0.26,0.3,0.2,0.2])))
print(multivariate_normal_cdf(model_1_mu, model_1_sigma, np.array([0.5,0.7,0.9,0.8,0.28])))


PDF value: 0.06794114034470018
[0.26541827 0.26958986 0.30208302 0.23773875 0.20121529]
[[ 1.34696746e-02  8.25401038e-03 -5.89112022e-03 -1.87510744e-03
   1.98400606e-03]
 [ 8.25401038e-03  2.05968681e-02  1.95016003e-03  5.13469229e-05
   9.49667704e-03]
 [-5.89112022e-03  1.95016003e-03  1.12095266e-02  8.36871607e-03
  -3.00219346e-03]
 [-1.87510744e-03  5.13469229e-05  8.36871607e-03  2.15117542e-02
  -8.45532548e-03]
 [ 1.98400606e-03  9.49667704e-03 -3.00219346e-03 -8.45532548e-03
   1.96966587e-02]]
True
690.5937500228486
0.6994207043965714


In [126]:

n, d, k = 100, 2, 2
np.random.seed(20)
X = rand(n, d)
#print(X)
means = [rand(d) * 0.5 + 0.5 , - rand(d)  * 0.5 + 0.5]  # mean for first model and second model| Basically here we make the mean not so far away 
#from our random data X we generated, note that X is comprised of two Gaussian vectors of n = 100 .i.e we have two gaussian distributions (bivariate)
#later we can even plot it
print(means)

S = np.diag(rand(d))
print(S)


sigmas = [S]*k # This is the sigma of the first model and the second model
print(sigmas[1])

[array([0.69872366, 0.75176984]), array([0.25997411, 0.14504062])]
[[0.01764816 0.        ]
 [0.         0.06360523]]
[[0.01764816 0.        ]
 [0.         0.06360523]]


Now we basically have 2 Random Gaussian vectors $\in R^{100}$ We put them in matrix $X$ that is in our case $X \in R^{100\times 2}$

Note: In theory this is actually $X^T$ as $X \in R^{2\times100}$

We also have two Models that are not far off from the original data (This only serves for visualisation purposes, but in reality they need not depend on the data at all)



In [143]:
def compute_log_p(X, mean, sigma):
    d = X.shape[1]
    dxm = X - mean
    exponent = -0.5 * np.sum(dxm * np.dot(dxm, np.linalg.inv(sigma)), axis=1)
    return exponent - np.log(2 * np.pi) * (d / 2) - 0.5 * np.log(np.linalg.det(sigma))

#log_ps = [compute_log_p(X, m, s) for m, s in zip(means, sigmas)]  # exercise: try to do this without looping

#print(log_ps[0])
#print(log_ps[1])

#print(log_ps[0] > log_ps[1])
#print(means[1])
multivariate_normal_pdf(means[0], sigmas[0], X)
means[0]

ValueError: shapes (2,100) and (2,2) not aligned: 100 (dim 1) != 2 (dim 0)