In [2]:
import numpy as np

## TASK A: Matrix standardisation function 

In [59]:
def normalise(matrix):
    result = np.zeros(matrix.shape) # careful to make a copy!
    matrix = matrix.astype(float)  # Convert the matrix to float data type
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            result[i, j] = (matrix[i, j] - np.mean(matrix[:, j])) / np.std(matrix[:, j])
    return result

#Vectorized version subtracts vectors from matrices using broadcasting
def normalise_vectorized(matrix):
    column_means = np.mean(matrix, axis=0)
    column_std = np.std(matrix, axis=0)
    standardized_matrix = (matrix - column_means) / column_std
    return standardized_matrix

# Example usage
myMatrix = np.array([[80, 77, 3], [23, 2, 3], [95, 5, 6], [30, 8, 9]])
print(normalise(myMatrix))
print(normalise_vectorized(myMatrix))


[[ 0.74058808  1.7280553  -0.90453403]
 [-1.09478239 -0.67202151 -0.90453403]
 [ 1.22358031 -0.57601843  0.30151134]
 [-0.86938601 -0.48001536  1.50755672]]
[[ 0.74058808  1.7280553  -0.90453403]
 [-1.09478239 -0.67202151 -0.90453403]
 [ 1.22358031 -0.57601843  0.30151134]
 [-0.86938601 -0.48001536  1.50755672]]


## Task B: Eucliden Distance function

In [65]:
myMatrixA = np.array([[1,2],[3,4],[5,6]])
myMatrixB = np.array([[2,3],[5,4],[9,6],[20,21]])

#Euclidean Distance
def euclideanDistance(matrixA, matrixB):
    distance = np.zeros((matrixA.shape[0], matrixB.shape[0]))
    for i in range(matrixA.shape[0]):
        for j in range(matrixB.shape[0]):
            distance[i,j] = np.sqrt(np.sum(np.square(matrixA[i] - matrixB[j])))
    return distance

euclideanDistance(myMatrixA, myMatrixB)

array([[ 1.41421356,  4.47213595,  8.94427191, 26.87005769],
       [ 1.41421356,  2.        ,  6.32455532, 24.04163056],
       [ 4.24264069,  2.        ,  4.        , 21.21320344]])

Task C: 